# RENOMBRAS UNA TABLA #
ALTER TABLE USUARIOS RENAME TO USUARIOS_RENOM;

# CAMBIAR NOMBRE DE UNA COLUMNA #
ALTER TABLE USUARIOS_RENOM CHANGE apellidos apellido varchar(100) NULL;

# MODIFICAR COLUMNA SIN CAMBIAR NOMBRE
ALTER TABLE USUARIOS_RENOM MODIFY apellido CHAR(50) NOT NULL;

# AÑADIR COLUMNA #
ALTER TABLE USUARIOS_RENOM ADD website VARCHAR(100) NULL;

# AÑADIR RESTRICCION A COLUMNA #
ALTER TABLE USUARIOS_RENOM ADD CONSTRAINT USUARIOS_RENOM_email_UK UNIQUE(email);

# BORRAR UNA COLUMNA #
ALTER TABLE USUARIOS_RENOM DROP website;
