CREATE TABLE USUARIOS(
id INT(255) auto_increment NOT NULL,
nombre VARCHAR(100) NOT NULL,
apellidos VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL,
password VARCHAR(255) NOT NULL,
fecha DATE NOT NULL,
CONSTRAINT USUARIOS_PK PRIMARY KEY(id),
CONSTRAINT USUARIOS_email_UK UNIQUE(email)
)ENGINE = InnoDb;

CREATE TABLE CATEGORIAS(
id INT(255) AUTO_INCREMENT NOT NULL,
nombre VARCHAR(100),
CONSTRAINT CATEGORIAS_PK PRIMARY KEY(id)
)ENGINE = InnoDb;

CREATE TABLE ENTRADAS(
id INT(255) AUTO_INCREMENT NOT NULL,
usuario_id INT(255) NOT NULL,
categoria_id INT(255) NOT NULL,
titulo VARCHAR(255) NOT NULL,
descripcion MEDIUMTEXT,
fecha DATE NOT NULL,
CONSTRAINT ENTRADAS_PK PRIMARY KEY(id),
CONSTRAINT ENTRADAS_usuario_id_FK FOREIGN KEY(usuario_id) REFERENCES USUARIOS(id),
CONSTRAINT ENTRADAS_categoria_id_FK FOREIGN KEY(categoria_id) REFERENCES CATEGORIAS(id) ON DELETE SET NULL
)ENGINE = InnoDb;