# MOSTRAR TODOS REGISTROS / FILAS DE UNA TABLA #
SELECT email, nombre, apellidos FROM USUARIOS;

# MOSTRAR TODOS LOS CAMPOS#
SELECT * FROM USUARIOS;

# OPERADORES ARITMETICOS#
SELECT id, email, (7+7) AS 'OPERACION' FROM USUARIOS
ORDER BY id;

SELECT id, email, (id+7) AS 'OPERACION' FROM USUARIOS
ORDER BY id;

# FUNCIONES MATEMATICAS#
SELECT ABS(7) AS 'OPERACION' FROM USUARIOS;

# FUNCIONES PARA TEXTO#
SELECT UPPER(CONCAT(nombre, ' ', apellidos)) AS 'CONVERSION' FROM USUARIOS;

SELECT TRIM(CONCAT('      ',nombre, ' ', apellidos,'     ')) AS 'CONVERSION' FROM USUARIOS;

# FUNCIONES PARA FECHAS#
SELECT email, fecha, CURDATE() AS 'Fecha actual' FROM USUARIOS;

SELECT email, DATEDIFF(fecha, CURDATE()) AS 'Dias Diferencia' FROM USUARIOS;

SELECT email, DAYNAME(fecha) as 'Nombre del dia' FROM USUARIOS;
SELECT email, DAYOFMONTH(fecha) as 'Dia del mes' FROM USUARIOS;
SELECT email, DAYOFWEEK(fecha) as 'Dia de la semana' FROM USUARIOS;
SELECT email, DAYOFYEAR(fecha) as 'Dia del año' FROM USUARIOS;
SELECT email, MONTH(fecha) as 'Mes' FROM USUARIOS;
SELECT email, YEAR(fecha) as 'Mes' FROM USUARIOS;
SELECT email, DAY(fecha) as 'Mes' FROM USUARIOS;
SELECT email, HOUR(fecha) as 'Mes' FROM USUARIOS;
SELECT email, CURTIME() as 'Hora Actual' FROM USUARIOS;
SELECT email, SYSDATE() as 'Fecha y Hora Actual' FROM USUARIOS;
SELECT email, DATE_FORMAT(fecha, '%d-%m-%Y' ) as 'Fecha formateada' FROM USUARIOS;

# Funciones Generales
SELECT email, ISNULL(apellidos) FROM USUARIOS;

SELECT email, STRCMP('HOLA', 'HOLA') FROM USUARIOS;

SELECT VERSION() FROM USUARIOS;

SELECT USER() FROM USUARIOS;

# OBTIENE LOS REGISTROS QUE NO SE REPITAN
SELECT DISTINCT USER() FROM USUARIOS;

SELECT DISTINCT DATABASE() FROM USUARIOS;

SELECT IFNULL(apellidos, 'ESTE CAMPO ESTA VACIO') FROM USUARIOS;